<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Film1.aspx.cs" Inherits="Film1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div class="cevre">
         <div class="baslik" >
             <h1 class="fl" style="margin: 10px 5px 5px; font-family: 'Source Sans Pro', sans-serif; color: rgb(0, 0, 0); text-rendering: optimizelegibility; font-weight: normal; font-size: 22px; line-height: 22px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><span content="Godzilla" itemprop="name">Godzilla</span></h1>
         </div>
        <div class="resim">
            <img src="Images/film1.jpg" /></div>
        <div class="yazi">
           
            <table style="width: 100%">
                <tr>
                    <td style="width: 86px">Vizyon Tarihi</td>
                    <td><strong style="font-weight: bold; color: rgb(130, 9, 30); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">16 Mayıs 2014</strong></td>
                </tr>
                <tr>
                    <td style="width: 86px">Yapımı</td>
                    <td><a href="#" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="2014 Filmleri">2014</a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>-<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/filmler/abd" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="ABD Filmleri">ABD</a></td>
                </tr>
                <tr>
                    <td style="width: 86px">Tür</td>
                    <td><a href="#" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="3 Boyutlu Filmleri"><span itemprop="genre">3 Boyutlu</span></a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>,&nbsp;<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/en-iyi-bilim-kurgu-filmleri" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Bilim Kurgu Filmleri"><span itemprop="genre">Bilim 
                        Kurgu</span></a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>,&nbsp;<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/en-iyi-aksiyon-filmleri" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Aksiyon Filmleri"><span itemprop="genre">Aksiyon</span></a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>,&nbsp;<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/en-iyi-macera-filmleri" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Macera Filmleri"><span itemprop="genre">Macera</span></a></td>
                </tr>
                <tr>
                    <td style="width: 86px">Süre</td>
                    <td><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">123<span class="Apple-converted-space">&nbsp;</span>Dak.</span></td>
                </tr>
                <tr>
                    <td style="width: 86px">Yönetmen</td>
                    <td><a href="#" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Yönetmene Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Gareth Edwards Filmleri"><span itemprop="name">Gareth Edwards</span></a></td>
                </tr>
                <tr>
                    <td style="width: 86px">Oyuncular</td>
                    <td><span itemprop="actors" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/55650/aaron-taylor-johnson" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Sanatçıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="Aaron Taylor-Johnson Filmleri"><span itemprop="name">Aaron Taylor-Johnson</span></a><span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span></span><span itemprop="actors" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/26485/juliette-binoche" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Sanatçıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="Juliette Binoche Filmleri"><span itemprop="name">Juliette 
                        Binoche</span></a><span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span></span><span itemprop="actors" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/27076/ken-watanabe" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Sanatçıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="Ken Watanabe Filmleri"><span itemprop="name">Ken 
                        Watanabe</span></a></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span></span><span itemprop="actors" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/56044/bryan-cranston" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Sanatçıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="Bryan Cranston Filmleri"><span itemprop="name">Bryan 
                        Cranston</span></a><span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span></span><span itemprop="actors" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/26920/david-strathairn" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Sanatçıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="David Strathairn Filmleri"><span itemprop="name">David 
                        Strathairn</span></a></span></td>
                </tr>
                <tr>
                    <td style="width: 86px">Senaryo</td>
                    <td><a href="#" onclick="chase('Film Sayfası', 'Film Detayları', 'Senariste Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="David Callaham Filmleri">David Callaham</a></td>
                </tr>
                <tr>
                    <td style="width: 86px">Yapımcı</td>
                    <td><span itemprop="producer" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/27394/jon-jashni" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Yapımcıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="Jon Jashni Filmleri"><span itemprop="name">Jon Jashni</span><span class="Apple-converted-space">&nbsp;</span></a></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span></span><span itemprop="producer" itemscope="" itemtype="http://schema.org/Person" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><a href="http://www.sinemalar.com/sanatci/440080/brian-rogers" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Yapımcıya Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34);" title="Brian Rogers Filmleri"><span itemprop="name">Brian 
                        Rogers</span></a></span></td>
                </tr>
            </table>
           
            </div>
     
        <div class="biyo">
            <table style="width: 100%">
                <tr>
                    <td>
                        <h2 style="margin: 10px 5px 5px; font-family: 'Source Sans Pro', sans-serif; color: rgb(85, 85, 85); text-rendering: optimizelegibility; font-weight: normal; font-size: 20px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Konusu</h2>
                    </td>
                </tr>
                <tr>
                    <td><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">Dünyanın en ünlü canavarı, insanlığın haddini aşarak yaptığı bilimsel çalışmalar sonucu ortaya çıkarak tüm insanların varlığını tehdit eden acımasız yaratıklarla mücadele ederek bizi koruyor.&nbsp;</span></td>
                </tr>
            </table>
        </div>

        
    </div>
</asp:Content>

