<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Film3.aspx.cs" Inherits="Film3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div class="cevre">
         <div class="baslik" >
             <h1 class="fl" style="margin: 10px 5px 5px; font-family: 'Source Sans Pro', sans-serif; color: rgb(0, 0, 0); text-rendering: optimizelegibility; font-weight: normal; font-size: 22px; line-height: 22px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Uzay Kuvvetleri 2911(3D) UK2911</h1>
         </div>
        <div class="resim">
            <img src="Images/film3.jpg" /> </div>
        <div class="yazi">
           
            <table style="width: 100%">
                <tr>
                    <td style="width: 100px">Vizyon Tarihi</td>
                    <td><strong style="font-weight: bold; color: rgb(130, 9, 30); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">16 Mayıs 2014</strong></td>
                </tr>
                <tr>
                    <td style="width: 100px">Yapımı</td>
                    <td><a href="http://www.sinemalar.com/filmler/2013" style="text-decoration: none; color: rgb(153, 153, 153); outline: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="2013 Filmleri">2013</a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>-<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/filmler/turkiye" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Türkiye Filmleri">Türkiye</a></td>
                </tr>
                <tr>
                    <td style="width: 100px">Tür</td>
                    <td><a href="http://www.sinemalar.com/en-iyi-animasyon-filmleri" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Animasyon Filmleri"><span itemprop="genre">Animasyon</span></a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>,&nbsp;<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/filmler/3-boyutlu" style="text-decoration: none; color: rgb(153, 153, 153); outline: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="3 Boyutlu Filmleri"><span itemprop="genre">3 
                        Boyutlu</span></a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>,&nbsp;<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/en-iyi-bilim-kurgu-filmleri" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Bilim Kurgu Filmleri"><span itemprop="genre">Bilim 
                        Kurgu</span></a><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>,&nbsp;<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.sinemalar.com/en-iyi-macera-filmleri" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Macera Filmleri"><span itemprop="genre">Macera</span></a></td>
                </tr>
                <tr>
                    <td style="width: 100px">Süre</td>
                    <td><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">90<span class="Apple-converted-space">&nbsp;</span>Dak.</span></td>
                </tr>
                <tr>
                    <td style="width: 100px">Yönetmen</td>
                    <td><a href="http://www.sinemalar.com/sanatci/652665/ahin-michael-derun" itemprop="url" onclick="chase('Film Sayfası', 'Film Detayları', 'Yönetmene Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Şahin Michael Derun Filmleri"><span itemprop="name">Şahin Michael Derun</span></a></td>
                </tr>
                <tr>
                    <td style="width: 100px">Seslendirenler</td>
                    <td><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">Murat Şen<span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>Umut 
                        Tabak<span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>Naci Taşdöğen<span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>Fatih 
                        Özacun<span class="Apple-converted-space">&nbsp;</span></span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">,&nbsp;</span><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);"><span class="Apple-converted-space">&nbsp;</span>Aydoğan Temel</span></td>
                </tr>
                <tr>
                    <td style="width: 100px">Senaryo</td>
                    <td><a href="http://www.sinemalar.com/sanatci/652665/ahin-michael-derun" onclick="chase('Film Sayfası', 'Film Detayları', 'Senariste Tıklama');" style="text-decoration: none; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" title="Şahin Michael Derun Filmleri">Şahin Michael Derun</a></td>
                </tr>
                <tr>
                    <td style="width: 100px">Yapımcı</td>
                    <td>-</td>
                </tr>
            </table>
           
            </div>
     
        <div class="biyo">
            <table style="width: 100%">
                <tr>
                    <td>
                        <h2 style="margin: 10px 5px 5px; font-family: 'Source Sans Pro', sans-serif; color: rgb(85, 85, 85); text-rendering: optimizelegibility; font-weight: normal; font-size: 20px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Konusu</h2>
                    </td>
                </tr>
                <tr>
                    <td><span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">Detroit&#39;in duvarlarla çevrili bir kenar mahallesi tam bir suç cennetine dönüşmüştür, hiçbir resmi görevlinin buraya girmesi mümkün değildir. Ancak Damien adlı bir polis memuru (Paul Walker), eski bir mahkumun yardımıyla içeri girecek, buranın lideri olan suç baronunu durdurmak için elinden geleni yapacaktır.</span><br style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" />
                        <span style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">Fransız yapımı Banlieu 13&#39;ün yeniden uyarlaması olan film, 2014 Mayıs ayında Türkiye&#39;de gösterime girecek.</span></td>
                </tr>
            </table>
        </div>

        
    </div>
</asp:Content>

